config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  resources :users do
      resources :roles
      resources :allowances
  end

  resources :time_periods

  root 'welcome#index'

  get 'calendar/:year/:month' => 'calendar#show', as: :month

  get 'planner' => 'planner#show', as: :planner

  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout
  match '/auth/:provider/callback', :via => [:get, :post], :to => 'sessions#create'
  match '/auth/failure',  :via => [:get, :post], :to => 'sessions#failure'

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController

    before_filter :authorize

    def show
        @day_0 = Date.new(params[:year].to_i, params[:month].to_i, 1)
        range = @day_0 .. (@day_0 + 1.month)
        @leave = @current_user.time_periods.overlapping(range).active.to_a
        @leave += TimePeriod.active.overlapping(range).where(:category => TimePeriod.categories[:bankholiday])
    end

    def month_params delta
        {:year => (@day_0 + delta).year, :month => (@day_0 + delta).month}
    end

    helper_method :month_params
end

app/helpers/calendar_helper.rb
module CalendarHelper

  TITLE_CLASS = ""

  def cell_class current_date
    classes = []
    classes << 'weekend' if (current_date.saturday? || current_date.sunday?)
    classes << 'today' if current_date.today?
    classes.join ' '
  end

  def calendar_title
    ->(start_date) {
      render partial: 'title', locals: {start_date: start_date}
    }
  end

  def calendar_link which
    ->(_, _) {
      render partial: 'page_link', locals: {
        arrow: (which == :prev ? "&laquo;" : "&raquo;"),
        delta: (which == :prev ? (-1.month) : (1.month)),
        which: which
      }
    }
  end

end

app/views/calendar/_page_link.html.erb
<%= link_to raw(arrow), month_params(delta), class: "small-2 columns button #{ which }" %>

app/views/calendar/_title.html.erb
<div class="small-8 columns calendar-title">
  <h2>
    <%= I18n.t("date.month_names")[start_date.month] %> <%= start_date.year %>
  </h2>
</div>

app/views/calendar/show.html.erb
<%= month_calendar start_date: @day_0,
                   events: @leave,
                   title: calendar_title,
                   table: { class: "month calendar row" },
                   td: ->(_, current_date) { {class: cell_class(current_date) } },
                   previous_link: calendar_link(:prev),
                   next_link:     calendar_link(:next) do |date, events| %>
  <div class="date">
    <span class="eby"><%= date.to_s :eby %></span>
    <% if events.any? {|e| e.includes(date) } %>
        <ul class="events">
            <% events.select{|e| e.includes(date)}.
                      sort_by{|e| e.start_date }.each do |time_off| %>
                <li class="clearfix <%= time_off.category %> <%= time_off.status %>">
                    <%= link_to time_off, :class => 'title button' do %>
                        <%= (time_off.comment && time_off.comment != '') ? time_off.comment : time_off.category %>
                    <% end %>
                </li>
            <% end %>
        </ul>
    <% else %>
        <%= link_to "Add leave", new_time_period_path(start_date: date), class: "button secondary" %>
    <% end %>
  </div>
<% end %>