config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  resources :users do
      resources :roles
      resources :allowances
  end

  resources :time_periods

  root 'welcome#index'

  get 'calendar/:year/:month' => 'calendar#show', as: :month

  get 'planner' => 'planner#show', as: :planner

  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout
  match '/auth/:provider/callback', :via => [:get, :post], :to => 'sessions#create'
  match '/auth/failure',  :via => [:get, :post], :to => 'sessions#failure'

end

app/models/user.rb
class User < ActiveRecord::Base

    has_many :allowances
    has_many :time_periods
    has_many :authorizations
    has_and_belongs_to_many :roles
    validates :identifier, :presence => true

    # TODO: deal with overlapping leave
    def holiday_taken_in year
        year_range = Date.new(year, 1, 1) .. Date.new(year, 12, 31)
        bank_hols = TimePeriod.bankholiday.active.overlapping(year_range).to_a

        time_periods.active.holiday.overlapping(year_range).reduce(0) do |total, tp|
            clipped_end = [year_range.last, tp.end_date.to_date].min
            clipped_start = [year_range.first, tp.start_date.to_date].max
            r = clipped_start .. clipped_end
            holiday_discount = bank_hols.count do |h|
                r.include?(h.start_date) || r.include?(h.end_date) || (h.start_date .. h.end_date).cover?(r)
            end

            total + (clipped_end.jd - clipped_start.jd) - holiday_discount
        end

    end

    def has_day_off? date
        not time_periods.active.overlapping(date .. date).empty?
    end

    def has_role? name
        roles.find_by_name(name)
    end

    def admin?
        has_role? 'admin'
    end

    def add_role name
        roles << Role.find_or_create_by(name: name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  before_action :check_authorized, only: [:show, :edit, :update, :destroy]

  before_action :check_admin, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def check_authorized
      unless (@user.id == @current_user.id) || @current_user.admin?
        render :status => :forbidden, :text => "Permission denied"
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:identifer)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifier %><br>
    <%= f.text_area :identifier %>
  </div>
  <div class="actions">
    <%= f.submit class: "button right" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>User listing</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.identifier %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'View all', users_path, class: "button cancel left" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container user-details">
    <div class="row">
        <p class="medium-4 columns">
            <strong>Identifier:</strong>
            <%= @user.identifier %>
        </p>
        <p class="medium-4 columns">
            <strong>Email:</strong>
            <%= @user.email %>
        </p>
        <div class="medium-4 columns">
            <ul class="right button-group">
                <li>
                <%= link_to 'Edit', edit_user_path(@user), class: :button %>
                </li><li>
                <%= link_to 'Back', users_path, class: :button %>
                </li>
            </ul>
        </div>
    </div>

    <div class="row clearfix">
    <div class="large-12 columns">

        <% unless @user.roles.empty? %>
            <h3>Roles:</h3>
            <ul class="inline-list">
                <% @user.roles.each do |role| %>
                    <li>
                        <span class="label role">
                            <%= role.name %>
                            <% if @current_user.admin? %>
                                <%= link_to "x", user_role_path(@user, role), method: :delete, data: {confirm: 'Remove role?'} %>
                            <% end %>
                        </span>
                    </li>
                <% end %>
            </ul>
        <% end %>

        <% if @current_user.admin? %>
            <%= link_to 'Add role', new_user_role_path(@user), class: "right button tiny" %>
        <% end %>
    </div>
    </div>

    <div class="row clearfix">
    <div class="large-12 columns">
        <h3>Allowances:</h3>
        <% unless @user.allowances.empty? %>
            <table>
                <thead>
                    <tr>
                        <th>Year</th>
                        <th>Allowance</th>
                        <th>Remaining</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @user.allowances.each do |allowance| %>
                        <tr>
                            <td><%= allowance.year %></td>
                            <td><%= allowance.max_days %></td>
                            <td>
                                <% if allowance.year? and allowance.max_days? %>
                                    <%= allowance.max_days - @user.holiday_taken_in(allowance.year) %>
                                <% end %>
                            </td>
                            <td>
                                <ul class="right button-group tiny">
                                    <li>
                                        <%= link_to "Edit", edit_user_allowance_path(@user, allowance), class: "button tiny" %>
                                    </li>
                                    <li>
                                        <%= link_to "Delete", user_allowance_path(@user, allowance), method: :delete, class: "button tiny"%>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        <% end %>

        <% if @current_user.admin? %>
            <%= link_to 'Add allowance', new_user_allowance_path(@user), class: "button tiny right" %>
        <% end %>
    </div>
    </div>

</div>